### ISSUE TITLE
1.0.3 not working

### ISSUE THREAD

**Issue by GekoCH** [nancpasc/ZattooBox#35]
the plugin just updated and now i get this error
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('session',)
                                            Traceback (most recent call last):
                                              File "C:\Users\musik\AppData\Roaming\Kodi\addons\plugin.video.zattoobox\plugin.py", line 31, in <module>
                                                if zapiSession.init_session(kodi_addon.getSetting('username'), kodi_addon.getSetting('password')):
                                              File "C:\Users\musik\AppData\Roaming\Kodi\addons\plugin.video.zattoobox\resources\lib\core\zapisession.py", line 38, in init_session
                                                return (self.CACHE_ENABLED and self.restore_session()) or self.renew_session()
                                              File "C:\Users\musik\AppData\Roaming\Kodi\addons\plugin.video.zattoobox\resources\lib\core\zapisession.py", line 44, in restore_session
                                                if accountData['session'] is not None and accountData['success'] == True:
                                            KeyError: ('session',)
                                            -->End of Python script error report<--`

**Comment by nancpasc** [comment]
Hi, please delete the cache files manually (*.cache).

I will create a fix to handle this automatically in next version.

All best,
P.

**Comment by ghost** [comment]
ok thx this solved the problem

**Comment by sirsquall** [comment]
Where did you deleted the cache files?

**Comment by nancpasc** [comment]
From within Kodi, open the file manager from the settings. Browse to Profile directory / addon_data / plugin.video.zattoobox. You can delete the 3 files from here.

Otherwise the cache cleaning will be automatically done starting from commit #1.0.4, which will be available tomorrow.

All best,
P.
