### ISSUE TITLE
Python exception since Upgrade add-on to Python 3

### ISSUE THREAD

**Issue by cristofe47** [nancpasc/ZattooBox#42]
Hi there,

I am getting the following error when starting the Zattoo plugin:

2020-04-12 20:37:09.946 T:1417667456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/plugin.py", line 31, in <module>
                                                if zapiSession.init_session(kodi_addon.getSetting('username'), kodi_addon.getSetting('password')):
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/core/zapisession.py", line 38, in init_session
                                                return (self.CACHE_ENABLED and self.restore_session()) or self.renew_session()
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/core/zapisession.py", line 126, in renew_session
                                                return self.announce() and self.login()
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/core/zapisession.py", line 106, in announce
                                                params = {"client_app_token" : self.fetch_appToken(),
                                              File "/storage/.kodi/addons/plugin.video.zattoobox/resources/lib/core/zapisession.py", line 102, in fetch_appToken
                                                return re.search("window\.appToken\s*=\s*'(.*)'", html).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
2020-04-12 20:37:10.110 T:1426060160   ERROR: GetDirectory - Error getting plugin://plugin.video.zattoobox/
2020-04-12 20:37:10.111 T:1937690640   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zattoobox/) failed

Everything worked well last time I tried on Friday 10 April. I tried to delete the .cache files and to remove and reinstall the app but nothing helped.

I suspect the issue has to do with the move to python 3 (last commit 2 days ago).  I am using Libreelec 9.2.0 (Kodi 18.5), which uses python 2. According to https://forum.libreelec.tv/thread/11183-solved-raspi2-libreelec-python-3/ Kodi will move to Python 3 with v.19 only.

Thanks

**Comment by nancpasc** [comment]
Hi,

Which version of the plugin are you running ? The latest upgrade from the official repo should now work fine.

Best regards.
P.

**Comment by cristofe47** [comment]
Hi,

I had 1.0.5 (with automatic installation of new versions).

I manually updated to 1.0.6 from the official repository and the plugin is working fine again.

Thanks,
Christophe

**Comment by jgphpc** [comment]
Hi, 
I am not 100% sure this is the same issue but it looks the same:
```
File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.zattoobox/?ext=LiveTV&mode=watch&id=tsr1]
```

More details [here](http://ix.io/2yxj)
Is it an issue with ZattooBox or zapi or else ?

Thanks for the great add-on.

**Comment by cristofe47** [comment]
Hi jgphpc,

I don't *think* the issue is related to Python3, but I do see the same problem as you (I noticed it this morning).

This morning, I could start the plugin, but I could not access the channel list (neither "all" nor "favourite"). I see these errors in the Kodi logs:

LibreELEC:~/.kodi/temp # grep -i zattoobox kodi.old.log
2020-09-25 07:36:54.544 T:1936998416  NOTICE: ADDON: plugin.video.zattoobox v1.0.6 installed
2020-09-25 07:40:04.993 T:1438323584   ERROR: GetDirectory - Error getting plugin://plugin.video.zattoobox/?cat=fav&ext=LiveTV&mode=root
2020-09-25 07:40:04.996 T:1936998416   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zattoobox/?cat=fav&ext=LiveTV&mode=root) failed
2020-09-25 07:41:06.725 T:1362289536  NOTICE: ADDON: plugin.video.zattoobox v1.0.6 installed
2020-09-25 07:41:16.684 T:1436541824   ERROR: GetDirectory - Error getting plugin://plugin.video.zattoobox/?cat=fav&ext=LiveTV&mode=root
2020-09-25 07:41:16.685 T:1936998416   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zattoobox/?cat=fav&ext=LiveTV&mode=root) failed


I tried to deinstall and re-install the plugin. Now the plugin does not start with the error "unable to start a session. Check your account settings"

I am 100% sure my account settings are correct (I can log in on Chrome).

The kodi log show this:
2020-09-25 19:04:49.981 T:1570243456  NOTICE: ADDON: plugin.video.zattoobox v1.0.6 installed
2020-09-25 19:12:05.119 T:1411736448   ERROR: GetDirectory - Error getting plugin://plugin.video.zattoobox/
2020-09-25 19:12:05.121 T:1937715216   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zattoobox/) failed
2020-09-25 19:13:29.524 T:1799328640   ERROR: GetDirectory - Error getting plugin://plugin.video.zattoobox/
2020-09-25 19:13:29.525 T:1937715216   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zattoobox/) failed
2020-09-25 19:13:36.284 T:1799328640   ERROR: GetDirectory - Error getting plugin://plugin.video.zattoobox/
2020-09-25 19:13:36.287 T:1937715216   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zattoobox/) failed

Thanks,
Christophe

**Comment by nancpasc** [comment]
The login problem is fixed in v1.0.7. I did not merge the python3 code upgrade in the official repository, as I won't make this add-on compatible with future versions of Kodi. Please consider using the Zattoo PVR Add-on for more advanced features; it's also actively maintained.

P.

**Comment by jgphpc** [comment]
> The login problem is fixed in v1.0.7

Thank you :+1:
